### ISSUE TITLE
Help on using Python API to make a Connector for HERE XYZ

### ISSUE THREAD

**Issue by omanges** [kineticadb/kinetica-api-python#8]
Hi, I am thinking of writing a connector for HERE XYZ which can be used to ingest data in Kinetica DB from HERE XYZ and vice versa as well using Python API. Can somebody help me get started to like how connectors work for Kinetica DB ?

**Comment by mmahmud** [comment]
Hi @omanges!  To get started with the Python API, our tutorial at https://www.kinetica.com/docs/tutorials/python_guide.html might be useful.  Currently, all our connectors use inherently faster languages like Java or C++, and the source code is available here at github.  You may choose to check them out; all the connector reposistories have the word connector in the name.  Each connector's code is chiefly guided by the third party's SDK.  For example, the nifi connector's code layout is very different from the spark connector's code layout because we must use NiFi's SDK and Spark's SDK, respectively, to integrate those 3rd party platforms to Kinetica.

Also, please ensure that the API you are using is aligned with the Kinetica server you're using.  For example, if you're using Kinetica 7.0.x.y, then please use the latest 7.0 API version (only the first two version componenets need to match).

Please let me know if you require any further assistance.  Thanks, and have fun!

**Comment by omanges** [comment]
@mmahmud  Thank You, I'll have a look, I'll also do some analysis for on this one’s something is more clear I'll start something. Till then I'll close this issue.
